language: node_js
node_js:
# We support Node versions down to v4, currently
- '6'
- '5'
- '4.4.5'
after_success:
# Report coverage only from one of the builds (the v6 one)
- node -v | grep -q 'v6' && npm run coveralls
